version: 2.1

executors:
  nodelts:
    docker:
      - image: cimg/node:12.18

jobs:
  prepare_dependencies:
    executor: nodelts
    steps:
      - checkout
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}-{{ epoch }}
      - store_artifacts:
          path: yarn.lock
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: nodelts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - prepare_dependencies
      - test:
          requires:
            - prepare_dependencies
