const fs = require('fs')
const path = require('path')

const { chromium, devices } = require('playwright')

const DEVICE = devices['iPhone 13 Pro']

const DOCUMENT_URL = {
  classes: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes',
  elements: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements',
}
const CODES_SELECTOR = {
  classes: '#alphabetical_index+div>ul>li>a>code',
  elements: '#index+div>ul>li>a>code',
}

/**
 * @typedef {import("playwright").BrowserContext} BrowserContext
 */

/**
 * @param {BrowserContext} context
 * @param {string} url
 * @param {string} selector
 * @returns {Promise<string[]>}
 */
const getPseudos = async (context, url, selector) => {
  const page = await context.newPage()
  await page.goto(url)
  const codeElements = await page.$$(selector)
  const codes = await Promise.all(
    codeElements.map((element) =>
      element.evaluate((node) =>
        node.innerText.split(/\s/)[0].replace(/^:+/, '')
      )
    )
  )

  return codes.filter((code) => code.indexOf('(') === -1)
}

;(async () => {
  const browser = await chromium.launch({
    args: ['--disable-dev-shm-usage', '--ipc=host'],
  })
  const context = await browser.newContext({
    ...DEVICE,
    locale: 'en-US',
  })
  const [classes, elements] = await Promise.all([
    getPseudos(context, DOCUMENT_URL.classes, CODES_SELECTOR.classes),
    getPseudos(context, DOCUMENT_URL.elements, CODES_SELECTOR.elements),
  ])
  await browser.close()

  const output = `/* DON'T EDIT THIS FILE. This is generated by 'scripts/update-pseudos.js' */
module.exports = {
  pseudoElements: [
${elements.map((e) => `    '${e}'`).join(',\n')},
  ],

  pseudoClasses: [
${classes.map((c) => `    '${c}'`).join(',\n')},
  ],
}
`
  fs.writeFileSync(path.resolve(__dirname, '../lib.js'), output, 'utf-8')
})()
